title: Systems Operational
description: Matthias Werners selten gepflegtes Blog über Computer und Menschen
author: Matthias Werner
logo: /static/img/avatar.png
github: https://werner-matthias.github.com/SysOp
about: Systems Operational

baseurl: ""
url: ""

allowsearch: true

#disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

#share:
#  twitter_username: \#
#  fb_appid: 000000000000


brand-color: #3d61af

enableTags: true
tagarray: []

paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
