############################################
# Site Settings
############################################
# Title of your website
title: "Systems Operational"

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Matthias Werners selten gepflegtes Blog über Computer und Menschen"

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Matthias Werners Blog. "

# Main author of the website
# See > authors.yml
author: mwerner

# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'http://localhost:4000/SysOp'
baseurl: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

future: true

# Paginates all X entries
paginate: 5

# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown

kramdown:
  input: GFM
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   sbquo,lsquo,bdquo,ldquo
  hard_wrap:      false
  footnote_nr:    1
  
permalink: pretty

highlighter: rouge

excerpt_separator: "<!--more-->"

include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md

# The language setting is used in /includes/header.html for html-settings
language: "de"

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  debugging: false
  ignore:
    envs: [development]

############################################
# Plugins
############################################
plugins:
  - rubypants	
  - jekyll-paginate
  - jekyll_github_sample
  - emoji_for_jekyll
  - jekyll-typogrify

jemoji:
   src: images/emoji

############################################
# Default Settings
############################################
defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "posts"
    values:
      layout: page-fullwidth
      comments: false           # change if staticman is stable
      author: mwerner           # Default author for pages
      show_meta: true 	        # Show metadata for all pages

############################################
# SEO
# Facebook-Optimization › http://j.mp/fb_optimize
############################################
# google_author:             ""
# google_site_verification:  ""
# bing_webmastertools_id:    ""
# alexa_verify_id:           ""

############################################
# Favicons
# Facebook-Optimization › http://j.mp/fb_optimize
############################################
#  Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#  More information » https://mathiasbynens.be/notes/touch-icons                                                    ______            _
favicon-32x32:                          "favicon-32x32.png"
touch-icon-192x192:                     "touch-icon-192x192.png"
apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
msapplication_tilecolor:                "#fabb00"


############################################
# Facebook
# Facebook-Optimization › http://j.mp/fb_optimize
############################################
# og_image:                         ""
# og_locale:                        "en_EN"
# og_type:                          "website"
# og_title:                         ""
# og_description:                   ""
# og_url:                           ""
# og_site_name:                     ""

############################################
# Disqus
# https://disqus.com
############################################
# used in _includes/comments
comments: false
# disqus_shortname: 

############################################
# Sass
############################################
# More › http://sass-lang.com/
#      > http://jekyllrb.com/docs/assets/#sassscss  

sass:
    sass_dir: _sass
    style: :compressed

############################################
# Analytics
# https://www.google.com/analytics/
############################################
# used in _includes/footer_scripts

# google_analytics_tracking_id: 


############################################
# twwl.to
# https://www.tawk.to/knowledgebase
############################################
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:
